### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled 

### ISSUE THREAD

**Issue by bw2497** [16lemoing/dot#9]
When I try to run the demo, there is AssertionError: Torch not compiled with CUDA enabled. Should I change to another torch version? My gpu is  4070ti so I guess its cuda version can support enough pytorch version.

**Comment by bw2497** [comment]
(dot) F:\DOT -track\dot>python demo.py --visualization_modes spaghetti_last_static --video_path orange.mp4
Traceback (most recent call last):
  File "F:\DOT -track\dot\demo.py", line 338, in <module>
    main(args)
  File "F:\DOT -track\dot\demo.py", line 286, in main
    model = create_model(args).cuda()
  File "C:\Users\Bo Wen\.conda\envs\dot\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Bo Wen\.conda\envs\dot\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Bo Wen\.conda\envs\dot\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Bo Wen\.conda\envs\dot\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\Users\Bo Wen\.conda\envs\dot\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\Bo Wen\.conda\envs\dot\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Bo Wen\.conda\envs\dot\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by 16lemoing** [comment]
Hi @bw2497 ! I don't see any reason why your GPU would not be supported. It is likely that you installed a CPU only version of pytorch. To check you can run:

```
import torch

print(torch.cuda.is_available())
print(torch.version.cuda)
```

If that is the case you will find a solution on pytorch forums.
